# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyTestSystemMainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainTestWindow(object):
    def setupUi(self, MainTestWindow):
        MainTestWindow.setObjectName("MainTestWindow")
        MainTestWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainTestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(150, 50, 580, 420))
        self.stackedWidget.setObjectName("stackedWidget")
        self.selectPage = QtWidgets.QWidget()
        self.selectPage.setObjectName("selectPage")
        self.tabWidget = QtWidgets.QTabWidget(self.selectPage)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 550, 400))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.selectTab_1 = QtWidgets.QWidget()
        self.selectTab_1.setObjectName("selectTab_1")
        self.selectTextBrowser_1 = QtWidgets.QTextBrowser(self.selectTab_1)
        self.selectTextBrowser_1.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.selectTextBrowser_1.setObjectName("selectTextBrowser_1")
        self.layoutWidget = QtWidgets.QWidget(self.selectTab_1)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 230, 441, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_1_1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_1_1.setObjectName("checkBox_1_1")
        self.select_1_ButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.select_1_ButtonGroup.setObjectName("select_1_ButtonGroup")
        self.select_1_ButtonGroup.addButton(self.checkBox_1_1)
        self.horizontalLayout.addWidget(self.checkBox_1_1)
        self.checkBox_1_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_1_2.setObjectName("checkBox_1_2")
        self.select_1_ButtonGroup.addButton(self.checkBox_1_2)
        self.horizontalLayout.addWidget(self.checkBox_1_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_1_3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_1_3.setObjectName("checkBox_1_3")
        self.select_1_ButtonGroup.addButton(self.checkBox_1_3)
        self.horizontalLayout_2.addWidget(self.checkBox_1_3)
        self.checkBox_1_4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_1_4.setObjectName("checkBox_1_4")
        self.select_1_ButtonGroup.addButton(self.checkBox_1_4)
        self.horizontalLayout_2.addWidget(self.checkBox_1_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.selectTab_1, "")
        self.selectTab_2 = QtWidgets.QWidget()
        self.selectTab_2.setObjectName("selectTab_2")
        self.selectTextBrowser_2 = QtWidgets.QTextBrowser(self.selectTab_2)
        self.selectTextBrowser_2.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.selectTextBrowser_2.setObjectName("selectTextBrowser_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.selectTab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 230, 441, 91))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.checkBox_2_1 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_2_1.setObjectName("checkBox_2_1")
        self.select_2_ButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.select_2_ButtonGroup.setObjectName("select_2_ButtonGroup")
        self.select_2_ButtonGroup.addButton(self.checkBox_2_1)
        self.horizontalLayout_13.addWidget(self.checkBox_2_1)
        self.checkBox_2_2 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_2_2.setObjectName("checkBox_2_2")
        self.select_2_ButtonGroup.addButton(self.checkBox_2_2)
        self.horizontalLayout_13.addWidget(self.checkBox_2_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.checkBox_2_3 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_2_3.setObjectName("checkBox_2_3")
        self.select_2_ButtonGroup.addButton(self.checkBox_2_3)
        self.horizontalLayout_14.addWidget(self.checkBox_2_3)
        self.checkBox_2_4 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_2_4.setObjectName("checkBox_2_4")
        self.select_2_ButtonGroup.addButton(self.checkBox_2_4)
        self.horizontalLayout_14.addWidget(self.checkBox_2_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.tabWidget.addTab(self.selectTab_2, "")
        self.selectTab_3 = QtWidgets.QWidget()
        self.selectTab_3.setObjectName("selectTab_3")
        self.selectTextBrowser_3 = QtWidgets.QTextBrowser(self.selectTab_3)
        self.selectTextBrowser_3.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.selectTextBrowser_3.setObjectName("selectTextBrowser_3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.selectTab_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(50, 230, 441, 91))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.checkBox_3_2 = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.checkBox_3_2.setObjectName("checkBox_3_2")
        self.select_3_ButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.select_3_ButtonGroup.setObjectName("select_3_ButtonGroup")
        self.select_3_ButtonGroup.addButton(self.checkBox_3_2)
        self.horizontalLayout_15.addWidget(self.checkBox_3_2)
        self.checkBox_3_1 = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.checkBox_3_1.setObjectName("checkBox_3_1")
        self.select_3_ButtonGroup.addButton(self.checkBox_3_1)
        self.horizontalLayout_15.addWidget(self.checkBox_3_1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.checkBox_3_3 = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.checkBox_3_3.setObjectName("checkBox_3_3")
        self.select_3_ButtonGroup.addButton(self.checkBox_3_3)
        self.horizontalLayout_16.addWidget(self.checkBox_3_3)
        self.checkBox_3_4 = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.checkBox_3_4.setObjectName("checkBox_3_4")
        self.select_3_ButtonGroup.addButton(self.checkBox_3_4)
        self.horizontalLayout_16.addWidget(self.checkBox_3_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.selectTab_3, "")
        self.selectTab_4 = QtWidgets.QWidget()
        self.selectTab_4.setObjectName("selectTab_4")
        self.selectTextBrowser_4 = QtWidgets.QTextBrowser(self.selectTab_4)
        self.selectTextBrowser_4.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.selectTextBrowser_4.setObjectName("selectTextBrowser_4")
        self.layoutWidget_4 = QtWidgets.QWidget(self.selectTab_4)
        self.layoutWidget_4.setGeometry(QtCore.QRect(50, 230, 441, 91))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.checkBox_4_1 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_4_1.setObjectName("checkBox_4_1")
        self.select_4_ButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.select_4_ButtonGroup.setObjectName("select_4_ButtonGroup")
        self.select_4_ButtonGroup.addButton(self.checkBox_4_1)
        self.horizontalLayout_17.addWidget(self.checkBox_4_1)
        self.checkBox_4_2 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_4_2.setObjectName("checkBox_4_2")
        self.select_4_ButtonGroup.addButton(self.checkBox_4_2)
        self.horizontalLayout_17.addWidget(self.checkBox_4_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.checkBox_4_3 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_4_3.setObjectName("checkBox_4_3")
        self.select_4_ButtonGroup.addButton(self.checkBox_4_3)
        self.horizontalLayout_18.addWidget(self.checkBox_4_3)
        self.checkBox_4_4 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_4_4.setObjectName("checkBox_4_4")
        self.select_4_ButtonGroup.addButton(self.checkBox_4_4)
        self.horizontalLayout_18.addWidget(self.checkBox_4_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.tabWidget.addTab(self.selectTab_4, "")
        self.selectTab_5 = QtWidgets.QWidget()
        self.selectTab_5.setObjectName("selectTab_5")
        self.selectTextBrowser_5 = QtWidgets.QTextBrowser(self.selectTab_5)
        self.selectTextBrowser_5.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.selectTextBrowser_5.setObjectName("selectTextBrowser_5")
        self.layoutWidget_5 = QtWidgets.QWidget(self.selectTab_5)
        self.layoutWidget_5.setGeometry(QtCore.QRect(50, 230, 441, 91))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.checkBox_5_1 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkBox_5_1.setObjectName("checkBox_5_1")
        self.select_5_ButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.select_5_ButtonGroup.setObjectName("select_5_ButtonGroup")
        self.select_5_ButtonGroup.addButton(self.checkBox_5_1)
        self.horizontalLayout_19.addWidget(self.checkBox_5_1)
        self.checkBox_5_2 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkBox_5_2.setObjectName("checkBox_5_2")
        self.select_5_ButtonGroup.addButton(self.checkBox_5_2)
        self.horizontalLayout_19.addWidget(self.checkBox_5_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.checkBox_5_3 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkBox_5_3.setObjectName("checkBox_5_3")
        self.select_5_ButtonGroup.addButton(self.checkBox_5_3)
        self.horizontalLayout_20.addWidget(self.checkBox_5_3)
        self.checkBox_5_4 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkBox_5_4.setObjectName("checkBox_5_4")
        self.select_5_ButtonGroup.addButton(self.checkBox_5_4)
        self.horizontalLayout_20.addWidget(self.checkBox_5_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.tabWidget.addTab(self.selectTab_5, "")
        self.selectTab_6 = QtWidgets.QWidget()
        self.selectTab_6.setObjectName("selectTab_6")
        self.selectTextBrowser_6 = QtWidgets.QTextBrowser(self.selectTab_6)
        self.selectTextBrowser_6.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.selectTextBrowser_6.setObjectName("selectTextBrowser_6")
        self.layoutWidget_6 = QtWidgets.QWidget(self.selectTab_6)
        self.layoutWidget_6.setGeometry(QtCore.QRect(50, 230, 441, 91))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.checkBox_6_1 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.checkBox_6_1.setObjectName("checkBox_6_1")
        self.select_6_ButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.select_6_ButtonGroup.setObjectName("select_6_ButtonGroup")
        self.select_6_ButtonGroup.addButton(self.checkBox_6_1)
        self.horizontalLayout_21.addWidget(self.checkBox_6_1)
        self.checkBox_6_2 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.checkBox_6_2.setObjectName("checkBox_6_2")
        self.select_6_ButtonGroup.addButton(self.checkBox_6_2)
        self.horizontalLayout_21.addWidget(self.checkBox_6_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.checkBox_6_3 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.checkBox_6_3.setObjectName("checkBox_6_3")
        self.select_6_ButtonGroup.addButton(self.checkBox_6_3)
        self.horizontalLayout_22.addWidget(self.checkBox_6_3)
        self.checkBox_6_4 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.checkBox_6_4.setObjectName("checkBox_6_4")
        self.select_6_ButtonGroup.addButton(self.checkBox_6_4)
        self.horizontalLayout_22.addWidget(self.checkBox_6_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        self.tabWidget.addTab(self.selectTab_6, "")
        self.selectTab_7 = QtWidgets.QWidget()
        self.selectTab_7.setObjectName("selectTab_7")
        self.selectTextBrowser_7 = QtWidgets.QTextBrowser(self.selectTab_7)
        self.selectTextBrowser_7.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.selectTextBrowser_7.setObjectName("selectTextBrowser_7")
        self.layoutWidget_7 = QtWidgets.QWidget(self.selectTab_7)
        self.layoutWidget_7.setGeometry(QtCore.QRect(50, 230, 441, 91))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.checkBox_7_1 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_7_1.setObjectName("checkBox_7_1")
        self.select_7_ButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.select_7_ButtonGroup.setObjectName("select_7_ButtonGroup")
        self.select_7_ButtonGroup.addButton(self.checkBox_7_1)
        self.horizontalLayout_23.addWidget(self.checkBox_7_1)
        self.checkBox_7_2 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_7_2.setObjectName("checkBox_7_2")
        self.select_7_ButtonGroup.addButton(self.checkBox_7_2)
        self.horizontalLayout_23.addWidget(self.checkBox_7_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.checkBox_7_3 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_7_3.setObjectName("checkBox_7_3")
        self.select_7_ButtonGroup.addButton(self.checkBox_7_3)
        self.horizontalLayout_24.addWidget(self.checkBox_7_3)
        self.checkBox_7_4 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_7_4.setObjectName("checkBox_7_4")
        self.select_7_ButtonGroup.addButton(self.checkBox_7_4)
        self.horizontalLayout_24.addWidget(self.checkBox_7_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_24)
        self.tabWidget.addTab(self.selectTab_7, "")
        self.selectTab_8 = QtWidgets.QWidget()
        self.selectTab_8.setObjectName("selectTab_8")
        self.selectTextBrowser_8 = QtWidgets.QTextBrowser(self.selectTab_8)
        self.selectTextBrowser_8.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.selectTextBrowser_8.setObjectName("selectTextBrowser_8")
        self.layoutWidget_8 = QtWidgets.QWidget(self.selectTab_8)
        self.layoutWidget_8.setGeometry(QtCore.QRect(50, 230, 441, 91))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.checkBox_8_1 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.checkBox_8_1.setObjectName("checkBox_8_1")
        self.select_8_ButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.select_8_ButtonGroup.setObjectName("select_8_ButtonGroup")
        self.select_8_ButtonGroup.addButton(self.checkBox_8_1)
        self.horizontalLayout_25.addWidget(self.checkBox_8_1)
        self.checkBox_8_2 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.checkBox_8_2.setObjectName("checkBox_8_2")
        self.select_8_ButtonGroup.addButton(self.checkBox_8_2)
        self.horizontalLayout_25.addWidget(self.checkBox_8_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_25)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.checkBox_8_3 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.checkBox_8_3.setObjectName("checkBox_8_3")
        self.select_8_ButtonGroup.addButton(self.checkBox_8_3)
        self.horizontalLayout_26.addWidget(self.checkBox_8_3)
        self.checkBox_8_4 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.checkBox_8_4.setObjectName("checkBox_8_4")
        self.select_8_ButtonGroup.addButton(self.checkBox_8_4)
        self.horizontalLayout_26.addWidget(self.checkBox_8_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_26)
        self.tabWidget.addTab(self.selectTab_8, "")
        self.selectTab_9 = QtWidgets.QWidget()
        self.selectTab_9.setObjectName("selectTab_9")
        self.selectTextBrowser_9 = QtWidgets.QTextBrowser(self.selectTab_9)
        self.selectTextBrowser_9.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.selectTextBrowser_9.setObjectName("selectTextBrowser_9")
        self.layoutWidget_9 = QtWidgets.QWidget(self.selectTab_9)
        self.layoutWidget_9.setGeometry(QtCore.QRect(50, 230, 441, 91))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.checkBox_9_1 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.checkBox_9_1.setObjectName("checkBox_9_1")
        self.select_9_ButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.select_9_ButtonGroup.setObjectName("select_9_ButtonGroup")
        self.select_9_ButtonGroup.addButton(self.checkBox_9_1)
        self.horizontalLayout_27.addWidget(self.checkBox_9_1)
        self.checkBox_9_2 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.checkBox_9_2.setObjectName("checkBox_9_2")
        self.select_9_ButtonGroup.addButton(self.checkBox_9_2)
        self.horizontalLayout_27.addWidget(self.checkBox_9_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_27)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.checkBox_9_3 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.checkBox_9_3.setObjectName("checkBox_9_3")
        self.select_9_ButtonGroup.addButton(self.checkBox_9_3)
        self.horizontalLayout_28.addWidget(self.checkBox_9_3)
        self.checkBox_9_4 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.checkBox_9_4.setObjectName("checkBox_9_4")
        self.select_9_ButtonGroup.addButton(self.checkBox_9_4)
        self.horizontalLayout_28.addWidget(self.checkBox_9_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_28)
        self.tabWidget.addTab(self.selectTab_9, "")
        self.selectTab_10 = QtWidgets.QWidget()
        self.selectTab_10.setObjectName("selectTab_10")
        self.selectTextBrowser_10 = QtWidgets.QTextBrowser(self.selectTab_10)
        self.selectTextBrowser_10.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.selectTextBrowser_10.setObjectName("selectTextBrowser_10")
        self.layoutWidget_10 = QtWidgets.QWidget(self.selectTab_10)
        self.layoutWidget_10.setGeometry(QtCore.QRect(50, 230, 441, 91))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.checkBox_10_1 = QtWidgets.QCheckBox(self.layoutWidget_10)
        self.checkBox_10_1.setObjectName("checkBox_10_1")
        self.select_10_ButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.select_10_ButtonGroup.setObjectName("select_10_ButtonGroup")
        self.select_10_ButtonGroup.addButton(self.checkBox_10_1)
        self.horizontalLayout_29.addWidget(self.checkBox_10_1)
        self.checkBox_10_2 = QtWidgets.QCheckBox(self.layoutWidget_10)
        self.checkBox_10_2.setObjectName("checkBox_10_2")
        self.select_10_ButtonGroup.addButton(self.checkBox_10_2)
        self.horizontalLayout_29.addWidget(self.checkBox_10_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_29)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem9)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.checkBox_10_3 = QtWidgets.QCheckBox(self.layoutWidget_10)
        self.checkBox_10_3.setObjectName("checkBox_10_3")
        self.select_10_ButtonGroup.addButton(self.checkBox_10_3)
        self.horizontalLayout_30.addWidget(self.checkBox_10_3)
        self.checkBox_10_4 = QtWidgets.QCheckBox(self.layoutWidget_10)
        self.checkBox_10_4.setObjectName("checkBox_10_4")
        self.select_10_ButtonGroup.addButton(self.checkBox_10_4)
        self.horizontalLayout_30.addWidget(self.checkBox_10_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_30)
        self.tabWidget.addTab(self.selectTab_10, "")
        self.selectTab_11 = QtWidgets.QWidget()
        self.selectTab_11.setObjectName("selectTab_11")
        self.selectTextBrowser_11 = QtWidgets.QTextBrowser(self.selectTab_11)
        self.selectTextBrowser_11.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.selectTextBrowser_11.setObjectName("selectTextBrowser_11")
        self.layoutWidget_11 = QtWidgets.QWidget(self.selectTab_11)
        self.layoutWidget_11.setGeometry(QtCore.QRect(50, 230, 441, 91))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.checkBox_11_1 = QtWidgets.QCheckBox(self.layoutWidget_11)
        self.checkBox_11_1.setObjectName("checkBox_11_1")
        self.select_11_ButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.select_11_ButtonGroup.setObjectName("select_11_ButtonGroup")
        self.select_11_ButtonGroup.addButton(self.checkBox_11_1)
        self.horizontalLayout_31.addWidget(self.checkBox_11_1)
        self.checkBox_11_2 = QtWidgets.QCheckBox(self.layoutWidget_11)
        self.checkBox_11_2.setObjectName("checkBox_11_2")
        self.select_11_ButtonGroup.addButton(self.checkBox_11_2)
        self.horizontalLayout_31.addWidget(self.checkBox_11_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_31)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem10)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.checkBox_11_3 = QtWidgets.QCheckBox(self.layoutWidget_11)
        self.checkBox_11_3.setObjectName("checkBox_11_3")
        self.select_11_ButtonGroup.addButton(self.checkBox_11_3)
        self.horizontalLayout_32.addWidget(self.checkBox_11_3)
        self.checkBox_11_4 = QtWidgets.QCheckBox(self.layoutWidget_11)
        self.checkBox_11_4.setObjectName("checkBox_11_4")
        self.select_11_ButtonGroup.addButton(self.checkBox_11_4)
        self.horizontalLayout_32.addWidget(self.checkBox_11_4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_32)
        self.tabWidget.addTab(self.selectTab_11, "")
        self.selectTab_12 = QtWidgets.QWidget()
        self.selectTab_12.setObjectName("selectTab_12")
        self.selectTextBrowser_12 = QtWidgets.QTextBrowser(self.selectTab_12)
        self.selectTextBrowser_12.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.selectTextBrowser_12.setObjectName("selectTextBrowser_12")
        self.layoutWidget_12 = QtWidgets.QWidget(self.selectTab_12)
        self.layoutWidget_12.setGeometry(QtCore.QRect(50, 230, 441, 91))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_12)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.checkBox_12_1 = QtWidgets.QCheckBox(self.layoutWidget_12)
        self.checkBox_12_1.setObjectName("checkBox_12_1")
        self.select_12_ButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.select_12_ButtonGroup.setObjectName("select_12_ButtonGroup")
        self.select_12_ButtonGroup.addButton(self.checkBox_12_1)
        self.horizontalLayout_33.addWidget(self.checkBox_12_1)
        self.checkBox_12_2 = QtWidgets.QCheckBox(self.layoutWidget_12)
        self.checkBox_12_2.setObjectName("checkBox_12_2")
        self.select_12_ButtonGroup.addButton(self.checkBox_12_2)
        self.horizontalLayout_33.addWidget(self.checkBox_12_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_33)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem11)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.checkBox_12_3 = QtWidgets.QCheckBox(self.layoutWidget_12)
        self.checkBox_12_3.setObjectName("checkBox_12_3")
        self.select_12_ButtonGroup.addButton(self.checkBox_12_3)
        self.horizontalLayout_34.addWidget(self.checkBox_12_3)
        self.checkBox_12_4 = QtWidgets.QCheckBox(self.layoutWidget_12)
        self.checkBox_12_4.setObjectName("checkBox_12_4")
        self.select_12_ButtonGroup.addButton(self.checkBox_12_4)
        self.horizontalLayout_34.addWidget(self.checkBox_12_4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_34)
        self.tabWidget.addTab(self.selectTab_12, "")
        self.selectTab_13 = QtWidgets.QWidget()
        self.selectTab_13.setObjectName("selectTab_13")
        self.selectTextBrowser_13 = QtWidgets.QTextBrowser(self.selectTab_13)
        self.selectTextBrowser_13.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.selectTextBrowser_13.setObjectName("selectTextBrowser_13")
        self.layoutWidget_13 = QtWidgets.QWidget(self.selectTab_13)
        self.layoutWidget_13.setGeometry(QtCore.QRect(50, 230, 441, 91))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget_13)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.checkBox_13_1 = QtWidgets.QCheckBox(self.layoutWidget_13)
        self.checkBox_13_1.setObjectName("checkBox_13_1")
        self.select_13_ButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.select_13_ButtonGroup.setObjectName("select_13_ButtonGroup")
        self.select_13_ButtonGroup.addButton(self.checkBox_13_1)
        self.horizontalLayout_35.addWidget(self.checkBox_13_1)
        self.checkBox_13_2 = QtWidgets.QCheckBox(self.layoutWidget_13)
        self.checkBox_13_2.setObjectName("checkBox_13_2")
        self.select_13_ButtonGroup.addButton(self.checkBox_13_2)
        self.horizontalLayout_35.addWidget(self.checkBox_13_2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_35)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem12)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.checkBox_13_3 = QtWidgets.QCheckBox(self.layoutWidget_13)
        self.checkBox_13_3.setObjectName("checkBox_13_3")
        self.select_13_ButtonGroup.addButton(self.checkBox_13_3)
        self.horizontalLayout_36.addWidget(self.checkBox_13_3)
        self.checkBox_13_4 = QtWidgets.QCheckBox(self.layoutWidget_13)
        self.checkBox_13_4.setObjectName("checkBox_13_4")
        self.select_13_ButtonGroup.addButton(self.checkBox_13_4)
        self.horizontalLayout_36.addWidget(self.checkBox_13_4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_36)
        self.tabWidget.addTab(self.selectTab_13, "")
        self.selectTab_14 = QtWidgets.QWidget()
        self.selectTab_14.setObjectName("selectTab_14")
        self.selectTextBrowser_14 = QtWidgets.QTextBrowser(self.selectTab_14)
        self.selectTextBrowser_14.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.selectTextBrowser_14.setObjectName("selectTextBrowser_14")
        self.layoutWidget_14 = QtWidgets.QWidget(self.selectTab_14)
        self.layoutWidget_14.setGeometry(QtCore.QRect(50, 230, 441, 91))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget_14)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.checkBox_14_1 = QtWidgets.QCheckBox(self.layoutWidget_14)
        self.checkBox_14_1.setObjectName("checkBox_14_1")
        self.select_14_ButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.select_14_ButtonGroup.setObjectName("select_14_ButtonGroup")
        self.select_14_ButtonGroup.addButton(self.checkBox_14_1)
        self.horizontalLayout_37.addWidget(self.checkBox_14_1)
        self.checkBox_14_2 = QtWidgets.QCheckBox(self.layoutWidget_14)
        self.checkBox_14_2.setObjectName("checkBox_14_2")
        self.select_14_ButtonGroup.addButton(self.checkBox_14_2)
        self.horizontalLayout_37.addWidget(self.checkBox_14_2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_37)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem13)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.checkBox_14_3 = QtWidgets.QCheckBox(self.layoutWidget_14)
        self.checkBox_14_3.setObjectName("checkBox_14_3")
        self.select_14_ButtonGroup.addButton(self.checkBox_14_3)
        self.horizontalLayout_38.addWidget(self.checkBox_14_3)
        self.checkBox_14_4 = QtWidgets.QCheckBox(self.layoutWidget_14)
        self.checkBox_14_4.setObjectName("checkBox_14_4")
        self.select_14_ButtonGroup.addButton(self.checkBox_14_4)
        self.horizontalLayout_38.addWidget(self.checkBox_14_4)
        self.verticalLayout_14.addLayout(self.horizontalLayout_38)
        self.tabWidget.addTab(self.selectTab_14, "")
        self.selectTab_15 = QtWidgets.QWidget()
        self.selectTab_15.setObjectName("selectTab_15")
        self.selectTextBrowser_15 = QtWidgets.QTextBrowser(self.selectTab_15)
        self.selectTextBrowser_15.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.selectTextBrowser_15.setObjectName("selectTextBrowser_15")
        self.layoutWidget_15 = QtWidgets.QWidget(self.selectTab_15)
        self.layoutWidget_15.setGeometry(QtCore.QRect(50, 230, 441, 91))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layoutWidget_15)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.checkBox_15_1 = QtWidgets.QCheckBox(self.layoutWidget_15)
        self.checkBox_15_1.setObjectName("checkBox_15_1")
        self.select_15_ButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.select_15_ButtonGroup.setObjectName("select_15_ButtonGroup")
        self.select_15_ButtonGroup.addButton(self.checkBox_15_1)
        self.horizontalLayout_39.addWidget(self.checkBox_15_1)
        self.checkBox_15_2 = QtWidgets.QCheckBox(self.layoutWidget_15)
        self.checkBox_15_2.setObjectName("checkBox_15_2")
        self.select_15_ButtonGroup.addButton(self.checkBox_15_2)
        self.horizontalLayout_39.addWidget(self.checkBox_15_2)
        self.verticalLayout_15.addLayout(self.horizontalLayout_39)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem14)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.checkBox_15_3 = QtWidgets.QCheckBox(self.layoutWidget_15)
        self.checkBox_15_3.setObjectName("checkBox_15_3")
        self.select_15_ButtonGroup.addButton(self.checkBox_15_3)
        self.horizontalLayout_40.addWidget(self.checkBox_15_3)
        self.checkBox_15_4 = QtWidgets.QCheckBox(self.layoutWidget_15)
        self.checkBox_15_4.setObjectName("checkBox_15_4")
        self.select_15_ButtonGroup.addButton(self.checkBox_15_4)
        self.horizontalLayout_40.addWidget(self.checkBox_15_4)
        self.verticalLayout_15.addLayout(self.horizontalLayout_40)
        self.tabWidget.addTab(self.selectTab_15, "")
        self.stackedWidget.addWidget(self.selectPage)
        self.fillPage = QtWidgets.QWidget()
        self.fillPage.setObjectName("fillPage")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.fillPage)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 550, 400))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.fillTab_1 = QtWidgets.QWidget()
        self.fillTab_1.setObjectName("fillTab_1")
        self.fillTextBrowser_1 = QtWidgets.QTextBrowser(self.fillTab_1)
        self.fillTextBrowser_1.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.fillTextBrowser_1.setObjectName("fillTextBrowser_1")
        self.layoutWidget1 = QtWidgets.QWidget(self.fillTab_1)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 250, 195, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.fillLineEdit_1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.fillLineEdit_1.setObjectName("fillLineEdit_1")
        self.horizontalLayout_3.addWidget(self.fillLineEdit_1)
        self.tabWidget_2.addTab(self.fillTab_1, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.layoutWidget_16 = QtWidgets.QWidget(self.tab_18)
        self.layoutWidget_16.setGeometry(QtCore.QRect(30, 250, 195, 22))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_16)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_16)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.fillLineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget_16)
        self.fillLineEdit_2.setObjectName("fillLineEdit_2")
        self.horizontalLayout_4.addWidget(self.fillLineEdit_2)
        self.fillTextBrowser_2 = QtWidgets.QTextBrowser(self.tab_18)
        self.fillTextBrowser_2.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.fillTextBrowser_2.setObjectName("fillTextBrowser_2")
        self.tabWidget_2.addTab(self.tab_18, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.layoutWidget_17 = QtWidgets.QWidget(self.tab_17)
        self.layoutWidget_17.setGeometry(QtCore.QRect(30, 250, 195, 22))
        self.layoutWidget_17.setObjectName("layoutWidget_17")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_17)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_17)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.fillLineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget_17)
        self.fillLineEdit_3.setObjectName("fillLineEdit_3")
        self.horizontalLayout_5.addWidget(self.fillLineEdit_3)
        self.fillTextBrowser_3 = QtWidgets.QTextBrowser(self.tab_17)
        self.fillTextBrowser_3.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.fillTextBrowser_3.setObjectName("fillTextBrowser_3")
        self.tabWidget_2.addTab(self.tab_17, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.layoutWidget_18 = QtWidgets.QWidget(self.tab_19)
        self.layoutWidget_18.setGeometry(QtCore.QRect(30, 250, 195, 22))
        self.layoutWidget_18.setObjectName("layoutWidget_18")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_18)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_18)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.fillLineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_18)
        self.fillLineEdit_4.setObjectName("fillLineEdit_4")
        self.horizontalLayout_6.addWidget(self.fillLineEdit_4)
        self.fillTextBrowser_4 = QtWidgets.QTextBrowser(self.tab_19)
        self.fillTextBrowser_4.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.fillTextBrowser_4.setObjectName("fillTextBrowser_4")
        self.tabWidget_2.addTab(self.tab_19, "")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.layoutWidget_19 = QtWidgets.QWidget(self.tab_20)
        self.layoutWidget_19.setGeometry(QtCore.QRect(30, 250, 195, 22))
        self.layoutWidget_19.setObjectName("layoutWidget_19")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_19)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_19)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.fillLineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget_19)
        self.fillLineEdit_5.setObjectName("fillLineEdit_5")
        self.horizontalLayout_7.addWidget(self.fillLineEdit_5)
        self.fillTextBrowser_5 = QtWidgets.QTextBrowser(self.tab_20)
        self.fillTextBrowser_5.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.fillTextBrowser_5.setObjectName("fillTextBrowser_5")
        self.tabWidget_2.addTab(self.tab_20, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.layoutWidget_20 = QtWidgets.QWidget(self.tab_21)
        self.layoutWidget_20.setGeometry(QtCore.QRect(30, 250, 195, 22))
        self.layoutWidget_20.setObjectName("layoutWidget_20")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_20)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_20)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.fillLineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget_20)
        self.fillLineEdit_6.setObjectName("fillLineEdit_6")
        self.horizontalLayout_8.addWidget(self.fillLineEdit_6)
        self.fillTextBrowser_6 = QtWidgets.QTextBrowser(self.tab_21)
        self.fillTextBrowser_6.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.fillTextBrowser_6.setObjectName("fillTextBrowser_6")
        self.tabWidget_2.addTab(self.tab_21, "")
        self.tab_22 = QtWidgets.QWidget()
        self.tab_22.setObjectName("tab_22")
        self.layoutWidget_21 = QtWidgets.QWidget(self.tab_22)
        self.layoutWidget_21.setGeometry(QtCore.QRect(30, 250, 195, 22))
        self.layoutWidget_21.setObjectName("layoutWidget_21")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_21)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_21)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.fillLineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget_21)
        self.fillLineEdit_7.setObjectName("fillLineEdit_7")
        self.horizontalLayout_9.addWidget(self.fillLineEdit_7)
        self.fillTextBrowser_7 = QtWidgets.QTextBrowser(self.tab_22)
        self.fillTextBrowser_7.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.fillTextBrowser_7.setObjectName("fillTextBrowser_7")
        self.tabWidget_2.addTab(self.tab_22, "")
        self.tab_23 = QtWidgets.QWidget()
        self.tab_23.setObjectName("tab_23")
        self.layoutWidget_22 = QtWidgets.QWidget(self.tab_23)
        self.layoutWidget_22.setGeometry(QtCore.QRect(30, 250, 195, 22))
        self.layoutWidget_22.setObjectName("layoutWidget_22")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_22)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_22)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.fillLineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget_22)
        self.fillLineEdit_8.setObjectName("fillLineEdit_8")
        self.horizontalLayout_10.addWidget(self.fillLineEdit_8)
        self.fillTextBrowser_8 = QtWidgets.QTextBrowser(self.tab_23)
        self.fillTextBrowser_8.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.fillTextBrowser_8.setObjectName("fillTextBrowser_8")
        self.tabWidget_2.addTab(self.tab_23, "")
        self.tab_24 = QtWidgets.QWidget()
        self.tab_24.setObjectName("tab_24")
        self.layoutWidget_23 = QtWidgets.QWidget(self.tab_24)
        self.layoutWidget_23.setGeometry(QtCore.QRect(30, 250, 195, 22))
        self.layoutWidget_23.setObjectName("layoutWidget_23")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_23)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_23)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.fillLineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget_23)
        self.fillLineEdit_9.setObjectName("fillLineEdit_9")
        self.horizontalLayout_11.addWidget(self.fillLineEdit_9)
        self.fillTextBrowser_9 = QtWidgets.QTextBrowser(self.tab_24)
        self.fillTextBrowser_9.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.fillTextBrowser_9.setObjectName("fillTextBrowser_9")
        self.tabWidget_2.addTab(self.tab_24, "")
        self.tab_25 = QtWidgets.QWidget()
        self.tab_25.setObjectName("tab_25")
        self.layoutWidget_24 = QtWidgets.QWidget(self.tab_25)
        self.layoutWidget_24.setGeometry(QtCore.QRect(30, 250, 195, 22))
        self.layoutWidget_24.setObjectName("layoutWidget_24")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_24)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_24)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.fillLineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget_24)
        self.fillLineEdit_10.setObjectName("fillLineEdit_10")
        self.horizontalLayout_12.addWidget(self.fillLineEdit_10)
        self.fillTextBrowser_10 = QtWidgets.QTextBrowser(self.tab_25)
        self.fillTextBrowser_10.setGeometry(QtCore.QRect(10, 10, 521, 181))
        self.fillTextBrowser_10.setObjectName("fillTextBrowser_10")
        self.tabWidget_2.addTab(self.tab_25, "")
        self.stackedWidget.addWidget(self.fillPage)
        self.selectRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.selectRadioButton.setGeometry(QtCore.QRect(160, 10, 89, 16))
        self.selectRadioButton.setObjectName("selectRadioButton")
        self.switchButtonGroup = QtWidgets.QButtonGroup(MainTestWindow)
        self.switchButtonGroup.setObjectName("switchButtonGroup")
        self.switchButtonGroup.addButton(self.selectRadioButton)
        self.fillRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.fillRadioButton.setGeometry(QtCore.QRect(410, 10, 89, 16))
        self.fillRadioButton.setObjectName("fillRadioButton")
        self.switchButtonGroup.addButton(self.fillRadioButton)
        self.infoTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.infoTextBrowser.setGeometry(QtCore.QRect(10, 10, 121, 81))
        self.infoTextBrowser.setObjectName("infoTextBrowser")
        self.leftTimeTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.leftTimeTextBrowser.setGeometry(QtCore.QRect(10, 130, 121, 41))
        self.leftTimeTextBrowser.setObjectName("leftTimeTextBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label.setObjectName("label")
        self.leftTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.leftTextBrowser.setGeometry(QtCore.QRect(10, 220, 121, 41))
        self.leftTextBrowser.setObjectName("leftTextBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 81, 16))
        self.label_2.setObjectName("label_2")
        self.finishPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.finishPushButton.setGeometry(QtCore.QRect(20, 310, 101, 41))
        self.finishPushButton.setObjectName("finishPushButton")
        self.logoutPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutPushButton.setGeometry(QtCore.QRect(20, 380, 101, 41))
        self.logoutPushButton.setObjectName("logoutPushButton")
        MainTestWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainTestWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainTestWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainTestWindow)
        self.statusbar.setObjectName("statusbar")
        MainTestWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainTestWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainTestWindow)

    def retranslateUi(self, MainTestWindow):
        _translate = QtCore.QCoreApplication.translate
        MainTestWindow.setWindowTitle(_translate("MainTestWindow", "MainWindow"))
        self.checkBox_1_1.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_1_2.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_1_3.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_1_4.setText(_translate("MainTestWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectTab_1), _translate("MainTestWindow", "1"))
        self.checkBox_2_1.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_2_2.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_2_3.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_2_4.setText(_translate("MainTestWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectTab_2), _translate("MainTestWindow", "2"))
        self.checkBox_3_2.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_3_1.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_3_3.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_3_4.setText(_translate("MainTestWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectTab_3), _translate("MainTestWindow", "3"))
        self.checkBox_4_1.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_4_2.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_4_3.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_4_4.setText(_translate("MainTestWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectTab_4), _translate("MainTestWindow", "4"))
        self.checkBox_5_1.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_5_2.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_5_3.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_5_4.setText(_translate("MainTestWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectTab_5), _translate("MainTestWindow", "5"))
        self.checkBox_6_1.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_6_2.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_6_3.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_6_4.setText(_translate("MainTestWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectTab_6), _translate("MainTestWindow", "6"))
        self.checkBox_7_1.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_7_2.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_7_3.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_7_4.setText(_translate("MainTestWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectTab_7), _translate("MainTestWindow", "7"))
        self.checkBox_8_1.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_8_2.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_8_3.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_8_4.setText(_translate("MainTestWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectTab_8), _translate("MainTestWindow", "8"))
        self.checkBox_9_1.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_9_2.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_9_3.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_9_4.setText(_translate("MainTestWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectTab_9), _translate("MainTestWindow", "9"))
        self.checkBox_10_1.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_10_2.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_10_3.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_10_4.setText(_translate("MainTestWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectTab_10), _translate("MainTestWindow", "10"))
        self.checkBox_11_1.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_11_2.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_11_3.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_11_4.setText(_translate("MainTestWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectTab_11), _translate("MainTestWindow", "11"))
        self.checkBox_12_1.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_12_2.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_12_3.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_12_4.setText(_translate("MainTestWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectTab_12), _translate("MainTestWindow", "12"))
        self.checkBox_13_1.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_13_2.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_13_3.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_13_4.setText(_translate("MainTestWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectTab_13), _translate("MainTestWindow", "13"))
        self.checkBox_14_1.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_14_2.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_14_3.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_14_4.setText(_translate("MainTestWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectTab_14), _translate("MainTestWindow", "14"))
        self.checkBox_15_1.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_15_2.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_15_3.setText(_translate("MainTestWindow", "CheckBox"))
        self.checkBox_15_4.setText(_translate("MainTestWindow", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selectTab_15), _translate("MainTestWindow", "15"))
        self.label_3.setText(_translate("MainTestWindow", " 答案："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.fillTab_1), _translate("MainTestWindow", "1"))
        self.label_4.setText(_translate("MainTestWindow", " 答案："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_18), _translate("MainTestWindow", "2"))
        self.label_5.setText(_translate("MainTestWindow", " 答案："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_17), _translate("MainTestWindow", "3"))
        self.label_6.setText(_translate("MainTestWindow", " 答案："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_19), _translate("MainTestWindow", "4"))
        self.label_7.setText(_translate("MainTestWindow", " 答案："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_20), _translate("MainTestWindow", "5"))
        self.label_8.setText(_translate("MainTestWindow", " 答案："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_21), _translate("MainTestWindow", "6"))
        self.label_9.setText(_translate("MainTestWindow", " 答案："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_22), _translate("MainTestWindow", "7"))
        self.label_10.setText(_translate("MainTestWindow", " 答案："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_23), _translate("MainTestWindow", "8"))
        self.label_11.setText(_translate("MainTestWindow", " 答案："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_24), _translate("MainTestWindow", "9"))
        self.label_12.setText(_translate("MainTestWindow", " 答案："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_25), _translate("MainTestWindow", "10"))
        self.selectRadioButton.setText(_translate("MainTestWindow", "选择题"))
        self.fillRadioButton.setText(_translate("MainTestWindow", "填空题"))
        self.label.setText(_translate("MainTestWindow", "考试剩余时间"))
        self.label_2.setText(_translate("MainTestWindow", "已答/未答题目"))
        self.finishPushButton.setText(_translate("MainTestWindow", "交卷"))
        self.logoutPushButton.setText(_translate("MainTestWindow", "放弃"))
