
#考试界面UI部分

#考试界面的checkbox分别命名为checkBox_<选择题号>_<选项>
#考试界面的tabwidget的选择题tab页面分别命名为selectTab_<选择题号>
#考试界面选择题的textbrowser分别命名为selectTextBrowser_<选择题号>
#考试界面bottongroup分别命名为select_<选择题号>_ButtonGroup,switchButton

#考试界面用户信息的textbrowser命名为infoTextBrowser
#考试界面剩余时间的textbrowser命名为leftTimeTextBrowser
#考试界面剩余题目的textbrowser命名为leftTextBrowser

#考试界面交卷按钮的pushbutton命名为finishPushButton
#考试界面放弃按钮的pushbutton命名为logoutPushButton
#考试界面选择题切换按钮radiobutton命名为selectRadioButton
#考试界面填空题切换按钮radiobutton命名为fillRadioButton

#考试界面选择题的QWeidght的选择题page命名为selectPage
#考试界面填空题的QWeidght的选择题page命名为fillPage

#考试界面的tabwidget的填空题tab页面分别命名为fillTab_<填空题号>
#考试界面的填空题textbrowser分别命名为fillTextBrowser_<填空题号>


