# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cPyTestSystemPreparationUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreMainWindow(object):
    def setupUi(self, PreMainWindow):
        PreMainWindow.setObjectName("PreMainWindow")
        PreMainWindow.resize(800, 509)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PreMainWindow.sizePolicy().hasHeightForWidth())
        PreMainWindow.setSizePolicy(sizePolicy)
        PreMainWindow.setStyleSheet("background-color: rgba(161, 218, 250, 255);")
        self.centralwidget = QtWidgets.QWidget(PreMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 791, 461))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget_5)
        self.widget.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"等线\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("font: 75 10pt \"等线\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.preStuNameLabel = QtWidgets.QLabel(self.widget)
        self.preStuNameLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"宋体\";")
        self.preStuNameLabel.setObjectName("preStuNameLabel")
        self.verticalLayout_2.addWidget(self.preStuNameLabel)
        self.preStuGradeLabel = QtWidgets.QLabel(self.widget)
        self.preStuGradeLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"宋体\";")
        self.preStuGradeLabel.setObjectName("preStuGradeLabel")
        self.verticalLayout_2.addWidget(self.preStuGradeLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.logoutButton = QtWidgets.QPushButton(self.widget)
        self.logoutButton.setStyleSheet("font: 75 10pt \"等线\";\n"
"background-color: qlineargradient(spread:pad, x1:0.488364, y1:0, x2:0.495, y2:1, stop:0 rgba(213, 213, 213, 255), stop:1 rgba(250, 250, 250, 255));")
        self.logoutButton.setObjectName("logoutButton")
        self.horizontalLayout_2.addWidget(self.logoutButton)
        spacerItem1 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 75 10pt \"等线\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.noteTextBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget_5)
        self.noteTextBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noteTextBrowser.setObjectName("noteTextBrowser")
        self.verticalLayout_5.addWidget(self.noteTextBrowser)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.selectTestBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.selectTestBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selectTestBox.setObjectName("selectTestBox")
        self.selectTestBox.addItem("")
        self.selectTestBox.addItem("")
        self.horizontalLayout_7.addWidget(self.selectTestBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.mockTestPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.mockTestPushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.488364, y1:0, x2:0.495, y2:1, stop:0 rgba(213, 213, 213, 255), stop:1 rgba(250, 250, 250, 255));")
        self.mockTestPushButton.setObjectName("mockTestPushButton")
        self.horizontalLayout_8.addWidget(self.mockTestPushButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.officialTestPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.officialTestPushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.488364, y1:0, x2:0.495, y2:1, stop:0 rgba(213, 213, 213, 255), stop:1 rgba(250, 250, 250, 255));")
        self.officialTestPushButton.setObjectName("officialTestPushButton")
        self.horizontalLayout_8.addWidget(self.officialTestPushButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.gradeInfoPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.gradeInfoPushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.488364, y1:0, x2:0.495, y2:1, stop:0 rgba(213, 213, 213, 255), stop:1 rgba(250, 250, 250, 255));")
        self.gradeInfoPushButton.setObjectName("gradeInfoPushButton")
        self.horizontalLayout_8.addWidget(self.gradeInfoPushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.timeTextBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget_5)
        self.timeTextBrowser.setStyleSheet("font: 12pt \"黑体\";\n"
"background-color: rgb(255, 255, 255);")
        self.timeTextBrowser.setObjectName("timeTextBrowser")
        self.horizontalLayout_9.addWidget(self.timeTextBrowser)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        PreMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PreMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        PreMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PreMainWindow)
        self.statusbar.setObjectName("statusbar")
        PreMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PreMainWindow)
        QtCore.QMetaObject.connectSlotsByName(PreMainWindow)

    def retranslateUi(self, PreMainWindow):
        _translate = QtCore.QCoreApplication.translate
        PreMainWindow.setWindowTitle(_translate("PreMainWindow", "MainWindow"))
        self.label.setText(_translate("PreMainWindow", "学生姓名"))
        self.label_2.setText(_translate("PreMainWindow", "考生年级"))
        self.preStuNameLabel.setText(_translate("PreMainWindow", "NULL"))
        self.preStuGradeLabel.setText(_translate("PreMainWindow", "NULL"))
        self.logoutButton.setText(_translate("PreMainWindow", "注销登录"))
        self.label_6.setText(_translate("PreMainWindow", "考生注意事项："))
        self.selectTestBox.setItemText(0, _translate("PreMainWindow", "Python考试"))
        self.selectTestBox.setItemText(1, _translate("PreMainWindow", "MATLAB考试"))
        self.mockTestPushButton.setText(_translate("PreMainWindow", "模拟考试"))
        self.officialTestPushButton.setText(_translate("PreMainWindow", "正式考试"))
        self.gradeInfoPushButton.setText(_translate("PreMainWindow", "成绩信息"))
        self.label_5.setText(_translate("PreMainWindow", "当前时间"))
